version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - uploads:${TMP_IMAGE_DIRECTORY}
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - web-network
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis:7.0.0-alpine3.15
    networks:
      - web-network
networks:
  web-network:
volumes:
  uploads:
